intf_libs = # Interface dependencies.
impl_libs = # Implementation dependencies.

import intf_libs += libboost-asio%lib{boost_asio}
import intf_libs += libboost-beast%lib{boost_beast}
import intf_libs += libboost-url%lib{boost_url}

lib{forge}: {hxx ixx txx cxx}{** -version} \
            {hxx            }{    version} \
            $impl_libs $intf_libs

hxx{version}: in{version} $src_root/manifest

# Build options.
#
cxx.poptions =+ "-I$out_root" "-I$src_root"

obja{*}: cxx.poptions += -DLIBFORGE_STATIC_BUILD
objs{*}: cxx.poptions += -DLIBFORGE_SHARED_BUILD

# Export options.
#
lib{forge}:
{
  cxx.export.poptions = "-I$out_root" "-I$src_root"
  cxx.export.libs = $intf_libs
}

liba{forge}: cxx.export.poptions += -DLIBFORGE_STATIC
libs{forge}: cxx.export.poptions += -DLIBFORGE_SHARED

# For pre-releases use the complete version to make sure they cannot
# be used in place of another pre-release or the final version. See
# the version module for details on the version.* variable values.
#
if $version.pre_release
  lib{forge}: bin.lib.version = "-$version.project_id"
else
  lib{forge}: bin.lib.version = "-$version.major.$version.minor"

# Install into the libforge/ subdirectory of, say, /usr/include/
# recreating subdirectories.
#
{hxx ixx txx}{*}:
{
  install         = include/libforge/
  install.subdirs = true
}
